server:
  port: 9090

spring:
  security:
    oauth2:
      client:
        registration:
          admin-client:
            provider: workflow
            client-id: admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          workflow:
            issuer-uri: http://localhost:9000
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            user-name-attribute: sub